### ISSUE TITLE
IKEA Tradfri bulbs "pulse" when turned on

### ISSUE THREAD

**Issue by FezVrasta** [stefanwichmann/kelvin#30] opened 2018-02-28 12:40 UTC
I noticed that some of my Tradfri bulbs will pulse when turned on since I enabled Kelvin.

What could it be?

For pulse I mean, they "blink" slowly from say, 40% brightness to 100% brightness, it takes 5 or 6 seconds for the "pulse" to finish.

**Comment by stefanwichmann** [comment] 2018-02-28 16:00
Can you isolate any similarities for the lights that pulse and the ones that don't?

- Are all of them managed by Kelvin?
- Are they all on the same schedule?
- Are the all turned on in the same way? (physical switch vs. app for example)
- Do all lights have the same firmware?

Since I don't own any Tradfri lights I am not able to reproduce this behaviour myself and marked the issue as "help wanted". Is anyone experiencing the same issues?

If I have to guess, I would suspect an issue with the bulbs themself. Kelvin talks to the lights via the Hue Bridge and all lights are handled equally. So if some of them show this behaviour and others don't, I would start to look at the firmware.

**Comment by FezVrasta** [comment] 2018-02-28 16:02
They are all managed the same way and turned on the same way. I don't know if the Hue lights do the same because I don't use them a lot and the "pulse" thing happens randomly...

**Comment by stefanwichmann** [comment] 2018-04-19 13:46
Any update on the issue? I'm not sure how to help here...

**Comment by FezVrasta** [comment] 2018-04-19 13:47
Yeah I don't really know, I switched to the F.lux plugin for Home Assistant because of this problem and so far I haven't noticed any problem.

It's definitely a problem with this software.

**Comment by stefanwichmann** [comment] 2018-04-19 13:56
Strange! I'm sad to have to let you go like this...

I will close this issue until we have similar cases or more information where to look. Sorry!

**Closed by stefanwichmann** 2018-04-19 13:56 UTC
Labels: help wanted
